# Generated by Django 2.0.3 on 2019-03-22 14:37

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_messages', '0007_channel_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'ordering': ['channel_date']},
        ),
        migrations.AddField(
            model_name='channel',
            name='channel_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='channel',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='members', to=settings.AUTH_USER_MODEL),
        ),
    ]
